# fly.toml app configuration file generated for academaa on 2025-10-10T16:04:54-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'academaa'
primary_region = 'sjc'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'

[processes]
  app = 'node dist/index.js'
